# version: '3.8'

services:

  backend:
    build: ./services/backend
    ports:
      - 5000:5000
    environment:
      - DATABASE_URL=sqlite:///tmp/db/programari.db
      - SECRET_KEY=your_super_secret_key_here_change_in_production
    volumes:
      - ./services/backend:/app
      - backend_db:/tmp/db
    command: >
      sh -c "
      mkdir -p /tmp/db &&
      python apply_migration.py &&
      python migrations/test_data.py &&
      uvicorn src.main:app --reload --host 0.0.0.0 --port 5000
      "

  frontend:
    build: ./services/frontend
    volumes:
      - './services/frontend:/app'
      - '/app/node_modules'
    ports:
      - 8080:8080
    environment:
      - API_URL=http://localhost:5000


volumes:
  backend_db:
    driver: local